# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'Pixart' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SideMenu', '~> 6.0'
  pod 'ColorSlider', '~> 4.4'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'GoogleSignIn'
end
